### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by Dahandla** [GarrenSouza/GOAPFramework#1]
LoadErrors: Error: /Game/AI/Demo/LamberJack_BB : Can't find file for asset. /Game/Characters/AI/WorldGuardian/WorldGuardianBB

Also needed: Behavior Tree Utility Extension

Thank you

**Comment by GarrenSouza** [comment]
Hi Dahandla,
I'll take a look and fix it as soon as possible.

Thank you!

**Comment by GarrenSouza** [comment]
Hey Dahandla,
Well, the load error is gone. The Behavior Tree Utility Plugin can be found [right here](https://wiki.unrealengine.com/Behavior_Tree_Utility_Plugin), as described on the [project website](https://sites.google.com/view/goap-framework/goap) in the Installation section.

Have fun!
